all:
  children:
   geek:
     hosts:
      localhost:
   prodgeek:
     hosts:
       192.168.78.240: # тут должен быть ваш сервер
         ansible_user: roman







# [hosts]
# test_server   ansible_host=192.168.78.240  ansible_user=roman   ansible_ssh_private_key_file=/home/roman/.ssh/authorized_keys
# [localhost]
# 127.0.0.1
