- name: Add the group
  tags: ["group"]
  group:
    name: "{{ user_group }}"
    state: present    
- name: Add the user      
  tags: ["user"]
  user:
    name: "{{ user_name }}"
    password: "{{ user_password | password_hash('sha512') }}"
    shell: /bin/bash
    group: "{{ user_group }}"

