---
- name: Create directory struture
  file: 
    path: /home/app/{{ item }}
    state: directory
    mode: '0755'
  with_items: 
    - config
    - logs
    - data  

- name: Add some file at the directory
  file:        
    path: /home/app/config/{{ item }}
    state: touch
  with_items:
    - application.yml
    - cfg.ini
