[localhost]
127.0.0.1

[hosts]
test_node ansible_host=192.168.78.199  ansible_user=roman  ansible_ssh_private_key_file=/home/roman/.ssh/authorized_keys

[nginx]
test_nginx ansible_host=192.168.78.210 ansible_user=roman ansible_ssh_private_key_file=/home/roman/.ssh/authorized_keys
